### ISSUE TITLE
Could not navigate to 'petTypes'

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix-petclinic-2#6]
Jmix version: 2.4.0-RC1, 2.3.3
Jmix Studio plugin version: 2.4.SNAPSHOT6903-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Ultimate Edition)

TC
log in as oak
Master data -> pet type -> Select any pet

AR
![image](https://github.com/user-attachments/assets/e1ca3d87-560a-4bae-bd0f-612f638c048f)

**Comment by mariodavid** [comment]
I tried it locally and for me it worked. Nevertheless I changed the url to `/pet-types` to be more concise with the other urls.
